import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

export default function Home({ date }: { date: string }) {
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>{date}</div>
        <div>
          <div>
            <Link href="/city">Weather City(Rome)</Link>
          </div>
          <div>
            <Link href="/search">Weather Search</Link>
          </div>
        </div>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const date = new Date();
  const day = date.getDate();
  const month = date.getMonth() + 1;
  const year = date.getFullYear();
  const currentDate = `${day}-${month}-${year}`;

  return {
    props: {
      date: currentDate,
    },
  };
}
